---
title: "Generating Data from Distributions"
author: "Miles D. Williams"
date: "July 3, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Make vector of length 1,000, with sequence going from -4 to 4
x = seq(-4,4,len=1000)
    
# Get the probability density for a normal distribution centered at 0 over x
pdf = dnorm(x)
    
# Get the cumulative distribution for a normal distribution centered at 0 over x
cdf = pnorm(x)
    
# Generate random x values pulling from the normal distribution
random_x = rnorm(n = length(x), sd = 1, mean = 0)

# Generate random bivariate variable pulling from binomial distribution
binom_x = rbinom(n = length(x), size = 1, prob = .5)
```

Let's do some plots...

```{r}
plot(x,pdf) #,type="l")
```

```{r}
plot(x,cdf) #,type="l")
```

```{r}
hist(random_x)

density_random_x = density(random_x)
plot(density_random_x)
```

```{r}
cdf_random_x = ecdf(random_x)
plot(cdf_random_x)
```

```{r}
plot(cdf_random_x)
lines(density_random_x)
```

We can also make a prettier plot.

```{r}
# install.packages('extrafont') # If not already installed
# font_import() # only need to do first time
library(extrafont)
loadfonts(quiet = T)
par(family="Palatino Linotype",bty = "l")
plot(cdf_random_x, main = "Distributions Are Fun!",
     xlab = "Random Variable",
     ylab = "Density")
lines(density_random_x)
text(x = 1.8, y = .2, "p.d.f.")
text(x = .3, y = .8, "c.d.f.")
```

